### ISSUE TITLE
Offline Status on Discord

### ISSUE THREAD

**Issue by Fancykong123** [Migwel/tournify_discord_bot#1]
Hi!
Thank you for all of the work that you have put into TournifyBot! The Wii Fit Trainer discord heavily uses your bot for tournaments that we enter, and we noticed that it has been down for an extended period of time.

**Comment by Migwel** [comment]
@Fancykong123 I've started it again. Let me know if this happens again. I'm currently investigating ways to have it run more sustainably and receive notifications when the service is down
